%YAML:1.0
---
# board_size: [ 8, 7 ]
# /home/dyy/calibration_Audio_Technica_640x480/
# /home/dyy/calib_images/8x7_25mm/left/
# /home/dyy/calib_images/8x7_20mm_bino/left/
# /home/dyy/calib_images/8x7_47mm_bino/left/
# /home/dyy/calibration_roboteye/

# board_size: [ 9, 6 ]
# /home/dyy/calibration_640x480_HPWecam/
# /home/dyy/calibration_640x480/

# Path of images
image_path: /home/dyy/calibration_roboteye/

# Image resolution
image_size: [ 640, 480 ]

# Number of inner corners in chessboard
board_size: [ 8, 7 ]

# Length of square in chessboard in millimeter
square_size: 1
